<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $this->partial('partials/navbar'); ?>


<?php echo $this->getContent() ?>
<?php
    echo $this->tag->form(
        [
            "users/login",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<!--<div class="row">
    <div class="col-lg-4 col-xs-12">Username</div>
    <div class="col-lg-4 col-xs-12">Password</div>
</div>-->
<div class="row">
        <div class="col-xs-12 col-lg-4">
            <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername", 'placeholder' => 'Username']) ?>
        </div>

        <div class="col-xs-12 col-lg-4">
            <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword", 'placeholder' => 'Password']) ?>
        </div>

        <div class="col-xs-12 col-lg-4">
            <?php echo $this->tag->submitButton(["Login", "class" => "btn btn-default"]) ?>
            <?php echo $this->tag->linkTo(["users/new", "New user?"]) ?>
        </div>
</div>
<?php echo $this->tag->endForm(); ?>
