<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $this->partial('partials/navbar'); ?>

<?php echo $this->getContent(); ?>

<div class="row center-block">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->id ?></td>
                <td><?php echo $user->username ?></td>
                <td><?php echo $user->name ?></td>
                <td><?php echo $user->email ?></td>
                <td><?php echo $user->role ?></td>

                <td><?php echo $this->tag->linkTo(["users/edit/" . $user->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["users/delete/" . $user->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <ul class="pager">
                <li><?= $this->tag->linkTo(['users/index', 'First']) ?></li>
                <li><?= $this->tag->linkTo(['users/index?page=' . $page->before, 'Previous']) ?></li>
                <li><?= $this->tag->linkTo(['users/index?page=' . $page->next, 'Next']) ?></li>
                <li><?= $this->tag->linkTo(['users/index?page=' . $page->last, 'Last']) ?></li>
                <li><?= $page->current . '/' . $page->total_pages ?></li>
            </ul>
        </div>
    </div>
</div>
