<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $this->partial('partials/navbar'); ?>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<?php echo $this->getContent() ?>
<?php if (isset($page->items)) { ?>
    <?php foreach ($page->items as $post) { ?>
        <div class="row">
            <div class="col-lg-12 col-xs-12">
                <h2><?= $post->title ?></h2>
                <div><?= $post->body ?></div>
                <div><?= $this->tag->linkTo(['posts/show/' . $post->id, 'Show']); ?>
                    <?php if ($this->session->has("user_id")) {
                        #$user_id = $this->session->get('user_id');
                        if ($this->session->get('user_id') == $post->users_id) { ?>
                            <?= $this->tag->linkTo(['posts/edit/' . $post->id, 'Edit']); ?>
                            <?= $this->tag->linkTo(['posts/delete/' . $post->id, 'Delete']); ?>
                        <?php }} ?>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <ul class="pager">
                <li><?= $this->tag->linkTo(['posts/index', 'First']) ?></li>
                <li><?= $this->tag->linkTo(['posts/index?page=' . $page->before, 'Previous']) ?></li>
                <li><?= $this->tag->linkTo(['posts/index?page=' . $page->next, 'Next']) ?></li>
                <li><?= $this->tag->linkTo(['posts/index?page=' . $page->last, 'Last']) ?></li>
                <li><?= $page->current . '/' . $page->total_pages ?></li>
            </ul>
        </div>
    </div>
<?php } ?>
