<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../../index">KosTC</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="users" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="../../users">View</a></li>
                        <li><a href="../../users/new">Register</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Edit</a></li>
                    </ul>
                </li>
                <li class="dropdown active">
                    <a href="posts" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">View</a></li>
                        <li><a href="../new">Create</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Edit</a></li>
                    </ul>
                </li>
                <li>
                    <?php if ($this->session->has("user_id")){ ?>
                        <?= $this->tag->linkTo(['users/logout', 'Logout']); ?>
                    <?php } ?>
                    <?php if (!$this->session->has("user_id")){ ?>
                        <?= $this->tag->linkTo(['users', 'Login']); ?>
                    <?php } ?>
                </li>
            </ul>
            <?= $this->tag->form(['posts/search', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'navbar-form navbar-right']) ?>
            <div class="input-append">
                <?= $this->tag->textField(['body', 'class' => 'input-medium']) ?>
                <?= $this->tag->submitButton(['Search', 'class' => 'btn']) ?>
            </div>
            <?= $this->tag->endForm() ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <?= $this->getContent() ?>
    <div class="row">
        <div class="col-xs-12 col-lg-6">
            <h1>TITLE</h1>
            <p><h2><?= $post->title ?></h2></p>
        </div>

        <div class="row-xs-12 col-lg-6"
            <div class="row-xs-12 row-lg-12">
                <?= $post->body ?>
                <div class="row">
                    <h4>Tags</h4>
                    <?php foreach ($post->postTags as $posttag) { ?>
                        <?= $posttag->tags->tag ?>,
                    <?php } ?>
                </div>
            </div>
        <div><?= $this->tag->linkTo(['posts/edit/' . $post->id, 'Edit']) ?> | <?= $this->tag->linkTo(['posts/delete/' . $post->id, 'Delete']) ?></div>
    </div>
    <div class="row">
        <div class="comments">
            <h3>Comments</h3>
            <div class="comment">
                <?php foreach ($post->comments as $comments) { if ($comments->publish == true) { ?>
                    <div><?= $comments->body ?></div>
                    <div><?= $comments->name ?> - <?= $comments->submitted ?></div>
                <?php } ?><?php } ?>
            </div>
        </div>
        <div class="row">
            <h3>Leave a Comment</h3>
            <div>
                <?= $this->tag->form(['posts/comment', 'method' => 'post']) ?>
                <?= $this->tag->hiddenField(['posts_id', 'value' => $post->id]) ?>
                <div>
                    <label for="title">Comment</label>
                    <?= $this->tag->textArea(['body']) ?>
                </div>
                <div>
                    <label for="title">Name</label>
                    <?= $this->tag->textField(['name']) ?>
                </div>
                <div>
                    <label for="title">Email</label>
                    <?= $this->tag->textField(['email']) ?>
                </div>
                <div>
                    <label for="title">Website</label>
                    <?= $this->tag->textField(['url']) ?>
                </div>
                <?= $this->tag->submitButton(['Comment', 'class' => 'btn']) ?>
                <?= $this->tag->endForm() ?>
            </div>
        </div>
    </div>
</div>