<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search posts
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["posts/new", "Create posts"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "posts/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsersId" class="col-sm-2 control-label">Users</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["users_id", "type" => "number", "class" => "form-control", "id" => "fieldUsersId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["title", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBody" class="col-sm-2 control-label">Body</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["body", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldBody"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExcerpt" class="col-sm-2 control-label">Excerpt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["excerpt", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldExcerpt"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPublished" class="col-sm-2 control-label">Published</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["published", "size" => 30, "class" => "form-control", "id" => "fieldPublished"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdated" class="col-sm-2 control-label">Updated</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["updated", "size" => 30, "class" => "form-control", "id" => "fieldUpdated"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPinged" class="col-sm-2 control-label">Pinged</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["pinged", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldPinged"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldToPing" class="col-sm-2 control-label">To Of Ping</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["to_ping", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldToPing"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
