<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $this->partial('partials/navbar'); ?>

<div class="container-fluid">
    <div class="page-header">
        <h1>
            Edit posts
        </h1>
    </div>

    <?php echo $this->getContent(); ?>

    <?php
    echo $this->tag->form(
        [
            "comments/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
    ?>

    <div class="form-group">
        <label for="fieldBody" class="col-sm-2 control-label">Body</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textArea(["body", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldBody"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldName" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textArea(["name", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldName"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textArea(["email", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "email"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="publish" class="col-sm-2 control-label">Publish</label>
        <div class="col-sm-10">
            <?php echo $this->tag->select(['publish', ['Yes' => 'Yes', 'No' => 'No']]) ?>
        </div>
    </div>

    <?php echo $this->tag->hiddenField(id) ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
