
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php $this->partial('partials/navbar'); ?>

<?= $this->getContent() ?>
<h1>Comments</h1>

<div class="row center-block">
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>Body</th>
            <th>Name</th>
            <th>Email</th>
            <th>Submitted</th>
            <th>Publish</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php if (isset($page->items)) { ?>
            <?php foreach ($page->items as $comment) { ?>
                <tr>
                    <td><?= $comment->body ?></td>
                    <td><?= $comment->name ?></td>
                    <td><?= $comment->email ?></td>
                    <td><?= $comment->submitted ?></td>
                    <td><?= $comment->publish ?></td>
                    <td><?= $this->tag->linkTo(['comments/edit/' . $comment->id, 'Edit']) ?>
                    </td>
                    <td><?= $this->tag->linkTo(['comments/delete/' . $comment->id, 'Delete']) ?></td>
                </tr>
            <?php } ?>
        <?php } ?>
        </tbody>
    </table>
</div>

<div class="row center-block">
    <div class="col-xs-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-xs-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("comments/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("comments/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("comments/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("comments/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>