
<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index">KosTC</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="users" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="../users">View</a></li>
                        <li><a href="../users/new">Register</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Edit</a></li>
                    </ul>
                </li>
                <li class="dropdown active">
                    <a href="posts" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="posts/index">View</a></li>
                        <li><a href="posts/new">Create</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Edit</a></li>
                    </ul>
                </li>
                <li>
                    <?php if ($this->session->has("user_id")){ ?>
                        <?= $this->tag->linkTo(['users/logout', 'Logout']); ?>
                    <?php } ?>
                    <?php if (!$this->session->has("user_id")){ ?>
                        <?= $this->tag->linkTo(['users', 'Login']); ?>
                    <?php } ?>
                </li>
            </ul>
            <?= $this->tag->form(['posts/search', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'navbar-form navbar-right']) ?>
            <div class="input-append">
                <?= $this->tag->textField(['body', 'class' => 'input-medium']) ?>
                <?= $this->tag->submitButton(['Search', 'class' => 'btn']) ?>
            </div>
            <?= $this->tag->endForm() ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<?= $this->getContent() ?>
<h1>Comments</h1>
<table class="browse" align="center">
    <thead> <tr>
        <th>Body</th>
        <th>Name</th>
        <th>Email</th>
        <th>Url</th>
        <th>Submitted</th>
        <th>Publish</th>
    </tr>
    </thead>
    <tbody>
    <?php if (isset($page->items)) { ?>
        <?php foreach ($page->items as $comment) { ?>
            <tr>
                <td><?= $comment->body ?></td>
                <td><?= $comment->name ?></td>
                <td><?= $comment->email ?></td>
                <td><?= $comment->url ?></td>
                <td><?= $comment->submitted ?></td>
                <td><?= $comment->publish ?></td>
                <td><?= $this->tag->linkTo(['comments/edit/' . $comment->id, 'Edit']) ?>
                </td>
                <td><?= $this->tag->linkTo(['comments/delete/' . $comment->id, 'Delete']) ?></td>
            </tr>
        <?php } ?>
    <?php } ?>
    </tbody>
    <tbody><tr><td colspan="2" align="right">
            <table align="center">
                <tr>
                    <td><?= $this->tag->linkTo(['comments/search', 'First']) ?></td>
                    <td><?= $this->tag->linkTo(['comments/search?page=' . $page->before, 'Previous']) ?></td>
                    <td><?= $this->tag->linkTo(['comments/search?page=' . $page->next, 'Next']) ?></td>
                    <td><?= $this->tag->linkTo(['comments/search?page=' . $page->last, 'Last']) ?></td>
                    <td><?= $page->current . '/' . $page->total_pages ?></td>
                </tr>
            </table>
        </td></tr></tbody>
</table>