<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?= $this->tag->linkTo(['index/', 'type' => "button", 'class' => 'glyphicon glyphicon-home btn btn-lg btn-default', 'aria-hidden' => 'true']); ?>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php if ($this->session->has('user_id')) { ?>
                    <li class="navbar-text">Welcome, <?php echo $this->session->get('user_name'); ?> </li>
                <?php } ?>
                <?php if ($this->session->has("user_id") && $this->session->get('user_role') == 'Admin') { ?>
                    <li><?= $this->tag->linkTo(['users/index', 'Users']); ?></li>
                    <li><?= $this->tag->linkTo(['comments/index', 'Comments']); ?></li>
                <?php } ?>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><?= $this->tag->linkTo(['posts/index', 'View']); ?></li>
                        <li><?= $this->tag->linkTo(['posts/new', 'Create']); ?></li>
                    </ul>
                </li>
                <li>
                    <?php if($this->session->has('user_id')) { ?>
                    <?= $this->tag->linkTo(['users/edit/'.$this->session->get('user_id'), 'My Account']); ?>
                    <?php } ?>
                </li>
                <li>

                </li>
            </ul>
            <?php if ($this->session->has("user_id")){ ?>
                <?= $this->tag->linkTo(['users/logout', 'Logout', 'type' => 'button', 'class' => 'btn btn-default navbar-right']); ?>
            <?php } ?>
            <?php if (!$this->session->has("user_id")){ ?>
                <?= $this->tag->linkTo(['users/', 'Login', 'type' => 'button', 'class' => 'btn btn-default navbar-right']); ?>
            <?php } ?>
            <?= $this->tag->form(['posts/search', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'navbar-form navbar-right']) ?>
            <div class="input-append">
                <?= $this->tag->textField(['body', 'class' => 'input-medium']) ?>
                <?= $this->tag->submitButton(['Search', 'class' => 'btn']) ?>
            </div>
            <?= $this->tag->endForm() ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>