<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index">KosTC</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="users" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="users">View</a></li>
                        <li><a href="users/new">Register</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Edit</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="posts" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="posts">View</a></li>
                        <li><a href="posts/new">Create</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Edit</a></li>
                    </ul>
                </li>
            </ul>
            <?= $this->tag->form(['posts/search', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'navbar-form navbar-right']) ?>
            <div class="input-append">
                <?= $this->tag->textField(['body', 'class' => 'input-medium']) ?>
                <?= $this->tag->submitButton(['Search', 'class' => 'btn']) ?>
            </div>
            <?= $this->tag->endForm() ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="jumbotron">
    <h1>Kos TC</h1>
    <p>My TwitterClone APP</p>
</div>

<?php echo $this->getContent() ?>
<?php if (isset($page->items)) { ?>
    <?php foreach ($page->items as $post) { ?>
        <article>
            <h2><?= $post->title ?></h2>
            <div><?= $post->body ?></div>
            <div><?= $this->tag->linkTo(['posts/show/' . $post->id, 'Show']) ?></div>
        </article>
    <?php } ?>
    <ul class="pager">
        <li><?= $this->tag->linkTo(['posts/index', 'First']) ?></li>
        <li><?= $this->tag->linkTo(['posts/index?page=' . $page->before, 'Previous']) ?></li>
        <li><?= $this->tag->linkTo(['posts/index?page=' . $page->next, 'Next']) ?></li>
        <li><?= $this->tag->linkTo(['posts/index?page=' . $page->last, 'Last']) ?></li>
        <li><?= $page->current . '/' . $page->total_pages ?></li>
    </ul>
<?php } ?>


